/**
 * Dynamic Page Generation System
 *
 * Defines types and schemas for LLM-driven page generation
 */

/**
 * Page types supported by the system
 */
export type PageType = 'landing' | 'feature' | 'comparison' | 'dashboard' | 'custom'

/**
 * Layout types for page structure
 */
export type LayoutType = 'single-column' | 'two-column' | 'grid' | 'custom'

/**
 * Spacing options for layout
 */
export type SpacingType = 'compact' | 'normal' | 'spacious'

/**
 * Component size variants
 */
export type ComponentSize = 'sm' | 'md' | 'lg' | 'xl'

/**
 * Component theme variants
 */
export type ComponentTheme = 'light' | 'dark' | 'brand'

/**
 * Component priority levels
 */
export type ComponentPriority = 'primary' | 'secondary' | 'supporting'

/**
 * Breadcrumb navigation item
 */
export interface Breadcrumb {
  label: string
  href: string
}

/**
 * Component styling configuration
 */
export interface ComponentStyling {
  variant?: string
  size?: ComponentSize
  theme?: ComponentTheme
  className?: string
}

/**
 * Component metadata for generation insights
 */
export interface ComponentMetadata {
  purpose?: string
  priority?: ComponentPriority
}

/**
 * Individual component specification
 */
export interface ComponentSpec {
  id: string                          // Unique instance ID
  componentType: string               // Component registry key (e.g., 'hero-section')
  order: number                       // Render order (0-indexed)
  props: Record<string, any>          // Component-specific props
  content: any                        // Component content (structure varies)
  styling?: ComponentStyling
  metadata?: ComponentMetadata
}

/**
 * Page layout configuration
 */
export interface PageLayout {
  type: LayoutType
  components: ComponentSpec[]
  spacing?: SpacingType
}

/**
 * Page metadata for SEO and context
 */
export interface PageMetadata {
  title: string
  description: string
  keywords: string[]
  generatedFor: string                // Original user query
}

/**
 * Navigation suggestions for user guidance
 */
export interface PageNavigation {
  breadcrumbs?: Breadcrumb[]
  relatedQueries?: string[]
  nextSteps?: string[]
}

/**
 * Complete page specification generated by LLM
 */
export interface PageSpecification {
  id: string
  type: PageType
  metadata: PageMetadata
  layout: PageLayout
  navigation?: PageNavigation
  generatedAt: Date
  generatedBy: 'llm'
  llmModel: string                    // e.g., 'claude-3-haiku-20240307'
  generationTime: number              // milliseconds
}

/**
 * Page generation request
 */
export interface PageGenerationRequest {
  query: string                       // User's original query
  intent: string                      // Classified intent
  conversationHistory?: Array<{       // Recent conversation context
    role: 'user' | 'assistant'
    content: string
  }>
  persona?: string                    // Detected persona (if available)
  sessionId: string                   // Session identifier
}

/**
 * Page generation response
 */
export interface PageGenerationResponse {
  success: boolean
  pageSpec?: PageSpecification
  error?: string
  cached?: boolean                    // Whether result was from cache
}

/**
 * Component registry entry metadata
 */
export interface ComponentRegistryEntry {
  id: string
  name: string
  category: ComponentCategory
  description: string
  useCases: string[]
  tags: string[]
  props: Record<string, PropDefinition>
  contentStructure?: any
  examples?: ComponentExample[]
  personaVariants?: Record<string, VariantConfig>
}

/**
 * Component categories for organization
 */
export type ComponentCategory =
  | 'hero-headers'
  | 'content-information'
  | 'comparison-decision'
  | 'social-proof-trust'
  | 'interactive-engagement'
  | 'data-analytics'
  | 'technical-detailed'
  | 'navigation-guidance'
  | 'media-visual'
  | 'alerts-messaging'

/**
 * Prop definition for component registry
 */
export interface PropDefinition {
  type: string
  required: boolean
  description?: string
  default?: any
}

/**
 * Component usage example
 */
export interface ComponentExample {
  scenario: string
  componentType: string
  props: Record<string, any>
  content?: any
}

/**
 * Persona-specific component variant
 */
export interface VariantConfig {
  props?: Record<string, any>
  content?: any
  styling?: ComponentStyling
}

/**
 * Page generation error types
 */
export enum PageGenerationError {
  LLM_UNAVAILABLE = 'LLM_UNAVAILABLE',
  COMPONENT_NOT_FOUND = 'COMPONENT_NOT_FOUND',
  INVALID_SPECIFICATION = 'INVALID_SPECIFICATION',
  TIMEOUT = 'TIMEOUT',
  VALIDATION_FAILED = 'VALIDATION_FAILED'
}

/**
 * Page generation metrics for monitoring
 */
export interface PageGenerationMetrics {
  requestId: string
  query: string
  intent: string
  generationTime: number
  llmTokens: {
    input: number
    output: number
  }
  componentsGenerated: number
  cached: boolean
  success: boolean
  errorType?: PageGenerationError
  timestamp: Date
}
